spring.application.name=ecommerce
spring.profiles.active=dev-mysql

# Pedido config
pedido.corte.hora=20:00
pedido.zona.horaria=America/Lima

# Envío config
envio.zona.norte=5.00
envio.zona.sur=7.00
envio.monto.gratis=50.00
